#server:
#  port: 8080
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${RDS_USERNAME}
#    password: ${RDS_PASSWORD}
#    url: ${RDS_URL}
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 10
#
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#
#  data:
#    redis:
#      host: redis-cache
#      port: 6379
#
#logging:
#  level:
#    '[org.springframework.boot.web]': INFO
